module.exports = {
	root: true,
	parserOptions: {
		ecmaVersion: 6,
		sourceType: 'module',
	},
	parser: 'babel-eslint',
	extends: ['eslint:recommended', 'prettier'],
	env: {
		es6: true,
	},
	plugins: ['babel', 'prettier', 'import'],
	rules: {
		// Possible Errors
		'getter-return': 'error',
		'no-await-in-loop': 'error',
		'no-prototype-builtins': 'error',
		'no-template-curly-in-string': 'error',
		'valid-jsdoc': 'error',

		// Possible Errors - Overriding eslint:recommended
		'no-console': 'warn',
		'no-debugger': 'warn',

		// Stylistic Issues
		'consistent-this': ['error', 'that'],

		// Best practices
		curly: ['error', 'all'],
		'default-case': 'error',
		'dot-notation': 'error',
		eqeqeq: ['error', 'always'],
		'guard-for-in': 'error',
		'no-caller': 'error',
		'no-div-regex': 'error',
		'no-else-return': [
			'error',
			{
				allowElseIf: false,
			},
		],
		'no-eq-null': 'error',
		'no-eval': 'error',
		'no-extend-native': 'error',
		'no-extra-bind': 'error',
		'no-extra-label': 'error',
		'no-floating-decimal': 'error',
		'no-implicit-globals': 'error',
		'no-implied-eval': 'error',
		'no-invalid-this': 'error',
		'no-iterator': 'error',
		'no-labels': 'error',
		'no-lone-blocks': 'error',
		'no-loop-func': 'error',
		'no-multi-spaces': 'error',
		'no-multi-str': 'error',
		'no-octal-escape': 'error',
		'no-param-reassign': 'off',
		'no-proto': 'error',
		'no-restricted-properties': 'error',
		'no-return-assign': 'error',
		'no-return-await': 'error',
		'no-script-url': 'error',
		'no-self-compare': 'error',
		'no-sequences': 'error',
		'no-throw-literal': 'error',
		'no-unmodified-loop-condition': 'error',
		'no-unused-expressions': 'error',
		'no-useless-concat': 'warn',
		'no-useless-return': 'error',
		'no-void': 'error',
		'no-with': 'error',
		'prefer-promise-reject-errors': 'warn',
		radix: 'error',
		yoda: ['error', 'never', { onlyEquality: true }],

		// Variables
		'no-catch-shadow': 'error',
		'no-label-var': 'error',
		'no-shadow': 'error',
		'no-shadow-restricted-names': 'error',
		'no-use-before-define': 'error',

		// Stylistic Issues - Most are handled by prettier
		'func-names': ['error', 'as-needed'],
		'max-len': [
			'error',
			{
				code: 100,
				comments: 120,
				ignoreTemplateLiterals: true,
				ignoreUrls: true,
				ignoreComments: true,
				ignoreStrings: true,
			},
		],
		'new-cap': ['error', { properties: false }],
		'padding-line-between-statements': [
			'error',
			{ blankLine: 'always', prev: ['const', 'let', 'var'], next: '*' },
			{
				blankLine: 'any',
				prev: ['const', 'let', 'var'],
				next: '*',
			},
			{ blankLine: 'always', prev: 'directive', next: '*' },
			{ blankLine: 'any', prev: 'directive', next: 'directive' },
			{
				blankLine: 'always',
				prev: '*',
				next: [
					'return',
					'block',
					'block-like',
					'class',
					'switch',
					'for',
					'function',
					'throw',
				],
			},
		],

		// ECMAScript 6
		'no-confusing-arrow': ['error', { allowParens: true }],
		'prefer-arrow-callback': ['error', { allowNamedFunctions: true, allowUnboundThis: true }],
		'no-duplicate-imports': 'error',
		'no-useless-computed-key': 'error',
		'no-useless-rename': 'error',
		'no-var': 'error',
		'object-shorthand': 'error',
		'prefer-const': 'error',
		'prefer-spread': 'error',
		'prefer-template': 'error',
		'rest-spread-spacing': ['error', 'never'],
		'symbol-description': 'error',

		// Imports
		'import/no-extraneous-dependencies': ['error', { devDependencies: true }],
		'import/no-unresolved': 'error',
		'import/named': 'error',
		'import/default': 'error',
		'import/namespace': 'error',
		'import/no-absolute-path': 'error',
		'import/no-dynamic-require': 'error',
		'import/export': 'error',
		'import/no-mutable-exports': 'error',
		'import/first': 'error',
		'import/exports-last': 'error',
		'import/no-duplicates': 'error',
		'import/newline-after-import': ['error', { count: 1 }],
		'import/no-unassigned-import': 'error',
		'import/no-anonymous-default-export': [
			'error',
			{
				allowArray: false,
				allowArrowFunction: false,
				allowAnonymousClass: false,
				allowAnonymousFunction: false,
				allowLiteral: false,
				allowObject: false,
			},
		],
		// 'import/group-exports': 'error', // disabled for now

		// Prettier
		'prettier/prettier': [
			'warn',
			{
				bracketSpacing: true,
				jsxBracketSameLine: false,
				printWidth: 100,
				semi: true,
				singleQuote: true,
				tabWidth: 4,
				trailingComma: 'es5',
				useTabs: true,
			},
		],
	},
};
